# Generated by Django 4.2.5 on 2023-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankowner',
            name='mqtt_topic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
