# Generated by Django 4.2.5 on 2023-09-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.tankowner')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_phases', models.IntegerField()),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.processor')),
            ],
            options={
                'verbose_name_plural': 'Switches',
            },
        ),
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin_number', models.CharField(max_length=100)),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.switch')),
            ],
            options={
                'verbose_name': 'Water Pump',
            },
        ),
        migrations.CreateModel(
            name='WaterTankSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_level', models.FloatField()),
                ('max_capacity', models.FloatField()),
                ('min_threshold', models.FloatField()),
                ('sensor_pin_number', models.CharField(max_length=100)),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.processor')),
                ('water_pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.waterpump')),
            ],
            options={
                'verbose_name': 'Water Tank Sensor',
            },
        ),
        migrations.CreateModel(
            name='WaterValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin_number', models.CharField(max_length=100)),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('water_tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.watertanksensor')),
            ],
            options={
                'verbose_name': 'Solenoid Valve',
            },
        ),
    ]
