# Generated by Django 4.2.5 on 2023-09-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watertanksensor',
            options={'verbose_name': 'Water Tanks Sensor'},
        ),
        migrations.AlterModelOptions(
            name='watervalve',
            options={'verbose_name': 'Water Tanks Solenoid Valve'},
        ),
        migrations.AlterField(
            model_name='watervalve',
            name='water_tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watervalve', to='devices.watertanksensor'),
        ),
    ]
