# Generated by Django 4.2.5 on 2023-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_watervalve_water_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '_MQTTStatus',
                'verbose_name_plural': '_MQTTStatus',
            },
        ),
    ]
