# Generated by Django 4.2.5 on 2023-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_mqttstatus_started_at_mqttstatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='manual_mode',
            field=models.BooleanField(default=False),
        ),
    ]
