# Generated by Django 4.2.5 on 2023-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_processor_manual_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='manual_mode',
        ),
        migrations.AddField(
            model_name='waterpump',
            name='auto_mode',
            field=models.BooleanField(default=True),
        ),
    ]
