# Generated by Django 4.2.5 on 2023-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_switch_mqtt_topic_alter_watervalve_mqtt_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='name',
            field=models.CharField(default='NodeMCU', max_length=100),
            preserve_default=False,
        ),
    ]
