# Generated by Django 4.2.5 on 2023-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_processor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpump',
            name='mqtt_topic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
